development:
  adapter: async
    # adapter: redis
    # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
    # channel_prefix: backend_production


test:
  adapter: test

production:
  adapter: redis
  url: ENV['redis']
  #channel_prefix: backend_production
